#workflow name
name: sb-gh-cicd
on:
  #main event
  workflow_dispatch:
    inputs:
      username:
        description: 'Your GH username'
        required: true
      reason:
        description: 'Why are you running this workflow manually?'
        required: true
        default: 'I am running tests before implementing an automated workflow'
